### ISSUE TITLE
unrecognized arguments: --mpl-generate-path

### ISSUE THREAD

**Issue by cdeil** [astrofrog/pytest-mpl#6]
I tried following the instructions in the README, but I get this error:
```
$ cat test_a.py 
import pytest
import matplotlib.pyplot as plt

@pytest.mark.mpl_image_compare
def test_succeeds():
    fig = plt.figure()
    ax = fig.add_subplot(1,1,1)
    ax.plot([1,2,3])
    return fig
$ py.test --mpl-generate-path=images test_a.py 
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --mpl-generate-path=images
```

I did install it:
```
$ python -c 'import pytest_mpl'
```

**Comment by astrofrog** [comment]
@cdeil - could you try the absolute latest version? (I made some changes very recently to the command-line argument name). If it still doesn't work, what is the output of ``py.test --help``?

**Comment by cdeil** [comment]
I'm on the latest master: 6df019e944497be391133c3be74b2af60c252496

For some reason your plugin is not registering for me (Python 3.4 and py.test 2.7.1):
https://gist.github.com/cdeil/398d1de5603f77a7e4a8

Here's the output from `python setup.py install`:
https://gist.github.com/cdeil/301591bc5d45b1582035

**Comment by astrofrog** [comment]
This is weird - it seems that your py.test actually uses Python 2.7 - see the paths to the plugins:

  pytest-bench-0.2.5 at /Users/deil/Library/Python/**2.7**/lib/python/site-packages/pytest_bench/plugin.pyc

Maybe you don't have pytest installed in Python 3.4, so you installed the plugin in 3.4, but pytest is 2.7?

**Comment by cdeil** [comment]
@astrofrog – You're right ... I had this and didn't notice:
```
$ ls -lh /Users/deil/software/bin/py.test
lrwxr-xr-x  1 deil  staff    26B Apr 19  2014 /Users/deil/software/bin/py.test -> /opt/local/bin/py.test-2.7
```
So I remove it:
```
$ rm /Users/deil/software/bin/py.test
```
Now when I try to run the self-tests for this package:
https://gist.github.com/cdeil/a628d7d8d15ea5edeec5

Probably that was the reason I created that softlink last year ... some package required the command line tool to be named exactly `py.test`, but from Macports I get `py.test-2.7` and `py.test-3.4`.

I don't know if there's something that can be improved here ... close issue?

**Comment by astrofrog** [comment]
@cdeil - right, I think this is due to the MacPorts peculiarity, but not sure if I can avoid these failures. I'm going to go ahead and close this since this is not an issue with the functionality of the package itself, just the set-up for py.test.
